services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules # prevents overwriting node_modules from volume
    environment:
      - CHOKIDAR_USEPOLLING=true # helps hot reloading on some systems
